# Generated by Django 3.0.7 on 2021-05-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imago', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='isImago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='play',
            name='cover',
            field=models.ImageField(default=None, null=True, upload_to='covers', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='member',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
