# Generated by Django 3.0.8 on 2020-10-02 11:33

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
        ('imago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoExtended',
            fields=[
                ('photo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='photologue.Photo')),
            ],
            options={
                'abstract': False,
            },
            bases=('photologue.photo',),
        ),
        migrations.AddField(
            model_name='member',
            name='isImago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='play',
            name='cover',
            field=models.ImageField(default=None, null=True, upload_to='covers', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='member',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='GalleryExtended',
            fields=[
                ('gallery_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='photologue.Gallery')),
                ('images', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='extended_galleries', to='imago.PhotoExtended', verbose_name='photos')),
            ],
            bases=('photologue.gallery',),
        ),
        migrations.AddField(
            model_name='play',
            name='gallery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imago.GalleryExtended'),
        ),
    ]
