# Generated by Django 3.0.8 on 2020-10-09 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
        ('imago', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='isImago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='play',
            name='cover',
            field=models.ImageField(default=None, null=True, upload_to='covers', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='play',
            name='gallery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.Gallery'),
        ),
        migrations.AlterField(
            model_name='member',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
