# Generated by Django 3.0.5 on 2020-04-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imago', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='isImago',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='play',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
