# Generated by Django 3.0.5 on 2020-04-21 17:25

from django.db import migrations, models
import django.db.models.deletion
import imago.models


class Migration(migrations.Migration):

    dependencies = [
        ('imago', '0002_auto_20200420_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=imago.models.get_play_image_folder_name)),
                ('play', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='imago.Play')),
            ],
        ),
    ]
