# Generated by Django 3.0.5 on 2020-04-26 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
        ('imago', '0002_auto_20200420_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='cover',
        ),
        migrations.AddField(
            model_name='play',
            name='gallery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.Gallery'),
        ),
    ]
